# Generated by Django 3.0.7 on 2020-07-12 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenreM',
            fields=[
                ('movie_genre_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='映画ジャンルID')),
                ('movie_genre_name', models.CharField(max_length=20, verbose_name='映画ジャンル')),
            ],
            options={
                'verbose_name_plural': 'MovieGenreM',
            },
        ),
        migrations.CreateModel(
            name='MovieM',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='映画ID')),
                ('movie_title', models.CharField(max_length=40, verbose_name='映画タイトル')),
                ('released_date', models.DateField(verbose_name='公開日')),
                ('movie_summary', models.TextField(blank=True, null=True, verbose_name='あらすじ')),
                ('movie_genres', models.ManyToManyField(to='movie.MovieGenreM')),
            ],
            options={
                'verbose_name_plural': 'MovieM',
            },
        ),
        migrations.CreateModel(
            name='MovieWatchLaterT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.MovieM', verbose_name='映画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name_plural': 'MovieWatchLaterT',
            },
        ),
        migrations.CreateModel(
            name='MovieReviewT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateField(verbose_name='視聴日')),
                ('movie_score', models.IntegerField(verbose_name='点数')),
                ('movie_review', models.TextField(blank=True, null=True, verbose_name='レビュー')),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.MovieM', verbose_name='映画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name_plural': 'MovieReviewT',
            },
        ),
    ]
