# Generated by Django 2.0 on 2019-04-30 14:47

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'movie/migrations/fixture/MovieGenreM.json', app_label='movie')


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
